FROM python:3.12-slim
WORKDIR /app
# системные зависимости
RUN apt-get update && apt-get install -y \
    build-essential \
    ffmpeg \
    curl \
    libreoffice-nogui \
    ghostscript \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV PYTHONUNBUFFERED=1
CMD ["uvicorn", "app.web.app:app", "--host", "0.0.0.0", "--port", "8000"]