"""init_schema

Revision ID: 37f7b52f5964
Revises:
Create Date: 2026-02-21 13:17:59.873399

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37f7b52f5964"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure schema exists for all subsequent DDL.
    op.execute("CREATE SCHEMA IF NOT EXISTS eagle")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("plan", sa.String(length=16), nullable=False),
        sa.Column("premium_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("referred_by_id", sa.Integer(), nullable=True),
        sa.Column("referrals_count", sa.Integer(), nullable=False),
        sa.Column("active_tool", sa.String(length=32), nullable=True),
        sa.Column("audio_format", sa.String(length=8), nullable=False),
        sa.Column("mode_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("mode_message_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["referred_by_id"],
            ["eagle.users.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="eagle",
    )
    op.create_index(
        op.f("ix_eagle_users_tg_id"),
        "users",
        ["tg_id"],
        unique=True,
        schema="eagle",
    )

    op.create_table(
        "daily_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("used_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["eagle.users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "day", name="uq_daily_usage_user_day"),
        schema="eagle",
    )
    op.create_index(
        op.f("ix_eagle_daily_usage_day"),
        "daily_usage",
        ["day"],
        unique=False,
        schema="eagle",
    )
    op.create_index(
        op.f("ix_eagle_daily_usage_user_id"),
        "daily_usage",
        ["user_id"],
        unique=False,
        schema="eagle",
    )

    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("file_id", sa.String(length=255), nullable=True),
        sa.Column("result_path", sa.String(length=1024), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("extractor", sa.String(length=64), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["eagle.users.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="eagle",
    )
    op.create_index(
        op.f("ix_eagle_jobs_kind"),
        "jobs",
        ["kind"],
        unique=False,
        schema="eagle",
    )
    op.create_index(
        op.f("ix_eagle_jobs_status"),
        "jobs",
        ["status"],
        unique=False,
        schema="eagle",
    )
    op.create_index(
        op.f("ix_eagle_jobs_user_id"),
        "jobs",
        ["user_id"],
        unique=False,
        schema="eagle",
    )

    op.create_table(
        "referrals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("inviter_user_id", sa.Integer(), nullable=False),
        sa.Column("invited_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_user_id"],
            ["eagle.users.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["inviter_user_id"],
            ["eagle.users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="eagle",
    )
    op.create_index(
        op.f("ix_eagle_referrals_invited_user_id"),
        "referrals",
        ["invited_user_id"],
        unique=True,
        schema="eagle",
    )
    op.create_index(
        op.f("ix_eagle_referrals_inviter_user_id"),
        "referrals",
        ["inviter_user_id"],
        unique=False,
        schema="eagle",
    )

    op.create_table(
        "subscription_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("days_delta", sa.Integer(), nullable=False),
        sa.Column("meta", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["eagle.users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="eagle",
    )
    op.create_index(
        op.f("ix_eagle_subscription_events_user_id"),
        "subscription_events",
        ["user_id"],
        unique=False,
        schema="eagle",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_eagle_subscription_events_user_id"),
        table_name="subscription_events",
        schema="eagle",
    )
    op.drop_table("subscription_events", schema="eagle")

    op.drop_index(
        op.f("ix_eagle_referrals_inviter_user_id"),
        table_name="referrals",
        schema="eagle",
    )
    op.drop_index(
        op.f("ix_eagle_referrals_invited_user_id"),
        table_name="referrals",
        schema="eagle",
    )
    op.drop_table("referrals", schema="eagle")

    op.drop_index(op.f("ix_eagle_jobs_user_id"), table_name="jobs", schema="eagle")
    op.drop_index(op.f("ix_eagle_jobs_status"), table_name="jobs", schema="eagle")
    op.drop_index(op.f("ix_eagle_jobs_kind"), table_name="jobs", schema="eagle")
    op.drop_table("jobs", schema="eagle")

    op.drop_index(
        op.f("ix_eagle_daily_usage_user_id"),
        table_name="daily_usage",
        schema="eagle",
    )
    op.drop_index(op.f("ix_eagle_daily_usage_day"), table_name="daily_usage", schema="eagle")
    op.drop_table("daily_usage", schema="eagle")

    op.drop_index(op.f("ix_eagle_users_tg_id"), table_name="users", schema="eagle")
    op.drop_table("users", schema="eagle")
    # ### end Alembic commands ###